docs/content/docs/pub-sub-implementations.md, message/infrastructure/http/subscriber.go
It is sometimes necessary to add custom handlers to the HTTP subscriber (e.g. health check endpoint).
=> Add NewSubscriberWithRouter constructor to HTTP subscriber

docs/content/docs/pub-sub-implementations.md, message/infrastructure/nats/subscriber.go
The lack of default value causes ACK timeout immediately, if not supplied.
=> NATS: add default ack wait timeout

_examples/cqrs-protobuf/events.pb.go, message/infrastructure/nats/connection.go, message/infrastructure/nats/publisher.go, message/infrastructure/nats/streaming.go, message/infrastructure/nats/subscriber.go
Address issue: #57 
to resue Nats Streaming connection
Signed-off-by: Fan Shang Xiang <fanshangxiang@gmail.com>
=> add function for subscriber/publisher to reuse nats streaming connection

message/infrastructure/amqp/config.go, message/infrastructure/amqp/subscriber.go
We use the routing key in bindings.
The routing key is dynamic and in our example is an event name. Because the routing key is static, we don't have the flexibility we need.
In this PR, I change the variable to a function similar to routing keys in PublishConfig etc
=> make routing key dynamic in queue bind

message/infrastructure/amqp/config.go, message/infrastructure/amqp/connection.go, message/infrastructure/amqp/publisher.go, message/infrastructure/amqp/subscriber.go, message/infrastructure/amqp/topology_builder.go
Ou our RabbitMQ, we have topologies with 2 exchanges and we use routing keys to route the messages between exchanges/queues.
The problem we are facing is that we cannot configure 2 topologies currently. The fix adds a builder which can be easily replaced with a custom one.
There are no breaking changes.
=> Make configuring topology more flexible

message/router.go
Recoverer middleware should be used instead or panics should be handled by downstream code
=> Remove recover from handler

go.mod, go.sum, message/router/middleware/retry.go
Unfortunately v2 of the used backoff library violates the implementation of Go Modules.
I noticed that during testing go1.13beta1 and GOPROXY:
```shell
curl https://proxy.golang.org/github.com/cenkalti/backoff/@v/v2.2.0+incompatible.info
not found: github.com/cenkalti/backoff@v2.2.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```
Here is an issue discussing that: #76 
So I upgraded the backoff library.
Unfortunately, anyone using a go proxy suffers from this with RC1:
https://circleci.com/gh/goph/logur/75
=> Upgrade backoff library

message/router.go
Hey there! We had some problems with finding panic reason in our code. Added stack trace to error log.
=> Print stacktrace on panic recover.

message/router.go, message/router_test.go, pubsub/gochannel/pubsub.go, pubsub/gochannel/pubsub_test.go
This PR fixes data races reported by #111. They are related with concurrent closing of gochannel PubSub and Router.
=> Fix gochannel-related races

_examples/basic/1-your-first-app/go.mod, _examples/basic/1-your-first-app/go.sum, _examples/basic/1-your-first-app/main.go, _examples/basic/2-realtime-feed/consumer/go.mod, _examples/basic/2-realtime-feed/consumer/go.sum, _examples/basic/2-realtime-feed/consumer/main.go, _examples/basic/2-realtime-feed/producer/go.mod, _examples/basic/2-realtime-feed/producer/go.sum, _examples/basic/2-realtime-feed/producer/main.go, _examples/http-to-kafka/go.mod, _examples/http-to-kafka/go.sum, _examples/http-to-kafka/main.go, _examples/kafka-to-http/producer/go.mod, _examples/kafka-to-http/producer/go.sum, _examples/kafka-to-http/producer/main.go, _examples/kafka-to-http/router/go.mod, _examples/kafka-to-http/router/go.sum, _examples/kafka-to-http/router/main.go, _examples/sql/transactional-events/go.mod, _examples/sql/transactional-events/go.sum, _examples/sql/transactional-events/main.go, docs/content/docs/getting-started/kafka/go.mod, docs/content/docs/getting-started/kafka/go.sum, docs/content/docs/getting-started/kafka/main.go, docs/content/pubsubs/kafka.md, tools/mill/cmd/kafka.go, tools/mill/go.mod, tools/mill/go.sum
[watermill-kafka v2.0.0](https://github.com/ThreeDotsLabs/watermill-kafka/releases/tag/v2.0.0) introduced breaking changes to the constructors. This PR adopts all examples to the new API.
=> Bump examples to watermill-kafka v2.0.0

README.md
The separator just makes it a little easier to understand quickly.
=> Add thousands separator to benchmark results in README.md

_examples/real-world-examples/persistent-event-log/README.md, _examples/real-world-examples/transactional-events/README.md, docs/build.sh, docs/content/docs/middlewares.md, docs/content/pubsubs/sql.md, message/router.go, message/router_test.go
- Implemented Middleware per handler
- Added tests
=> Middleware per handler #133

message/router/middleware/duplicator.go, message/router/middleware/duplicator_test.go
Resolving https://github.com/ThreeDotsLabs/watermill/issues/131
=> Create middleware duplicating messages

message/context.go, message/context_test.go, message/router.go
part of https://github.com/ThreeDotsLabs/watermill-kafka/pull/8
related to https://github.com/ThreeDotsLabs/watermill/issues/69
Exposing subscribe and publish topics through `SubscribeTopicFromCtx` and `PublishTopicFromCtx` in the router.
=> add subscribe and publish topics to message context

pubsub/tests/test_pubsub.go
I was running into some errors when building a new subscriber due to subscribers continuing to log after a test has finished.
This changes ensures that the created multi-subscriber will be closed at the end of `TestConcurrentSubscribe`
=> Close all subscribers in TestConcurrentSubscribe

components/metrics/http.go, components/metrics/http_test.go, pubsub/gochannel/pubsub.go
The chi.Router is not used and I believe it is not intentional.
I have added tests to cover the expected behaviour. `go fmt` has added a small diff in `pubsub.go`.
Also out of curiosity, is there any benefit to do
```
wait := make(chan struct{})
go func() {
<-wait
server.Close()
}()
return func() { close(wait) }
```
instead of directly? 
```
return func() { server.Close() }
```
Thanks
=> Expose prometheus metrics at /metrics endpoint

components/metrics/builder.go
Accepting a prometheus.Registerer allows using prometheus.DefaultRegisterer.
=> Accept a Registerer instead of a Registry in PrometheusMetricsBuilder

pubsub/tests/test_pubsub.go
While working on an implementation for #126 (PostgreSQL driver with `SKIP LOCKED`), I found it necessary to initialize for each subscriber group. Therefore I needed to add the `SubscribeInitialize` in `generateConsumerGroup`, which is used by the test `TestConsumerGroups`.
=> Initialize subscribers for each consumer group

docs/content/pubsubs/firestore.md
Consumer groups are currently marked as supported here:
https://github.com/ThreeDotsLabs/watermill-firestore/blob/master/pkg/firestore/pubsub_test.go#L53
=> Mark consumer groups as supported

components/forwarder/envelope.go, components/forwarder/envelope_test.go
I've been using Forwarder's Publisher with one other Publisher wrapper (for setting correlation ID from message's Context). It turned out the order of wrapping matters: because the message's Context is not propagated.
This is a very specific case because the context will be lost anyway while marshaling the envelope. But for this one scenario, I guess it makes sense.
=> Pass Context to Forwarder's wrapped message

pubsub/tests/test_pubsub.go
Noticed one bad feature check (skipping if Persistent enabled, though message indicates ExactlyOnce intended).
Also added another to skip TestMessageCtx - this can also be addressed by calling publish the second time with a new message ID but I am not sure if that would invalidate the test in other situation?
=> Changes to Pubsub Test for ExactlyOnce

message/router.go, message/router_test.go
Exposed the registered router handlers to be used by a router plugin in order to allow use cases such as message reprocessing described in issue #288
=> [Added] Router handlers method for router plugins

message/router/middleware/recoverer.go, message/router/middleware/recoverer_test.go
- [Remove redundant multierror from Recoverer MW](https://github.com/ThreeDotsLabs/watermill/commit/e5fcffc5711e8cdc4f7f27947f3a2fe915f148cd)
- [Recover panics with nil value](https://github.com/ThreeDotsLabs/watermill/commit/a3f909914606b5d27aaa002a617132796b3c55b4)
=> Update Recoverer MW

pubsub/tests/test_pubsub.go
Update pubsub test setting (`TestConcurrentSubscribeMultipleTopics`) to resolve timeout error in GitHub Actions:
1. Reduced `topicsCount` from 50 to 20
2. Increased `bulkRead` timeout from `defaultTimeout` (15 secs) to `defaultTimeout*5` (75 secs)
=> Update pubsub test setting

_examples/basic/5-cqrs-protobuf/main.go, pubsub/doc.go, pubsub/gochannel/doc.go
in my understanding, `https://watermill.io/docs/pub-sub-implementations/` is expired now.
so I correct existing link. is this correct? 👓 
I'm not familiar with watermill. could you confirm at your convenience?
=> correct link of doc about pub/sub implementation supported by watermill

message/router.go
Initialization with `nil logger` will cause **panic** on Router run 
https://github.com/vladtenlive/watermill/blob/3867ad50830e3b50d13685243c68c331cd42ff32/message/router.go#L355
=> fix: router new logger panic

components/forwarder/envelope.go
This may be useful if the Forwarder's router middleware changes the Context in some way.
=> Forwarder: propagate the enveloped message's Context

docs/content/docs/forwarder.md
Just a small typo in the main doc page for the forwarder section.
=> fix: typo in forwarder.md

pubsub/tests/test_pubsub.go
Azure does only allow letters, digits and dash `-` (if not first, nor last) in the names of Storage Queues.
Closes #424
=> Change the autogenerated topic name to conform with Azure limits

docs/content/docs/awesome.md
The watermill-rediszset implements a Pub/Sub interface that can be beneficial in certain scenarios, such as scheduled tasks.
=> docs: add watermill-rediszset to unofficial libraries

message/router/middleware/deduplicator.go, message/router/middleware/deduplicator_test.go
Useful for many projects. If similar messages appear, discards all but the first one in a given time window.
=> Add deduplication middleware and publisher decorator

.github/workflows/master.yml, .github/workflows/pr-examples.yml, .github/workflows/tests.yml
This should resolve node deprecation warnings when viewing action results in the github UI.
=> ci: update setup-go and checkout to latest action versions

components/requestreply/backend_pubsub.go
Command reply topics can be ephemeral (e.g. tied to the lifetime of the service instance that published the command). In those cases an error publishing to the reply topic can be final, i.e. not recoverable by NACKing and retrying and would cause the reply message to spin needlessly. This change adds a configuration option in the form of a function callback that allows to inspect the error and optionally ignore it, while keeping the previous behavior (NACK unconditionally) as default.
=> Add configuration option to allow ignoring command reply publishing errors

_examples/pubsubs/googlecloud/go.sum, message/router.go
I have faced the race condition here when I was adding a handler with handler middleware while some concurrent process was calling RunHandlers. It is specified that RunHandlers is idempotent and there are locks for handlers, but not for middlewares.
Fixes https://github.com/ThreeDotsLabs/watermill/issues/466
=> Added lock for message.Router.middlewares

components/metrics/builder.go, components/metrics/handler.go, docs/content/docs/metrics.md
Allows user to configure the handler execution time histogram buckets and publish time histogram buckets; if not given, the default configuration is used.
closes #462
=> feat(metrics): custom histogram buckets configuration

message/router.go
Currently, the router will publish produced messaged by calling `Publish` individually, even though the bulk API exists.
This change works the same, although it can be handy for some custom implementations when you want to treat the produced messages as a group. For some implementations, it could also slightly improve publish performance.
=> Router: publish messages in bulk

.github/workflows/tests.yml
Watermill SQLite adapter has two go.mods, it doesn't work with the current setup.
Fix in SQLite adapter: https://github.com/ThreeDotsLabs/watermill-sqlite/pull/3
The resources of our team are limited. **There are a couple of things that you can do to help us merge your PR faster**:
- If you are testing a Pub/Sub, you can start Docker with `make up`.
- You can start with `make test_short` for a quick check.
- If you want to run all tests, use `make test`.
- Documentation is built in the [github.com/ThreeDotsLabs/watermill/docs](https://github.com/ThreeDotsLabs/watermill/tree/master/docs).
- You can find development instructions in the [DEVELOP.md](https://github.com/ThreeDotsLabs/watermill/tree/master/docs/DEVELOP.md).
=> Linter: Added support for multi-go.mod repos

docs/content/docs/message.md, message/message.go
This is the equivalent of calling `NewMessage()` and `SetContext()` separately, but should give a hint that when publishing messages, the message's context is used.
=> Add NewMessageWithContext()

docs/content/pubsubs/aws.md
Fix spelling error: 'ques' to 'queues' in SNS configuration documentatio
The resources of our team are limited. **There are a couple of things that you can do to help us merge your PR faster**:
- If you are testing a Pub/Sub, you can start Docker with `make up`.
- You can start with `make test_short` for a quick check.
- If you want to run all tests, use `make test`.
- Documentation is built in the [github.com/ThreeDotsLabs/watermill/docs](https://github.com/ThreeDotsLabs/watermill/tree/master/docs).
- You can find development instructions in the [DEVELOP.md](https://github.com/ThreeDotsLabs/watermill/tree/master/docs/DEVELOP.md).
=> docs: Fix spelling error: 'ques' to 'queues' in SNS configuration aws.md
